/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Semana11;

import javax.swing.JOptionPane;

/**
 *
 * @author RAT
 */
public class Principal_Pilas extends javax.swing.JFrame {

    //Variable global
    int tamaño;
    //Creación de objeto
    Pila P;

    public Principal_Pilas() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTamaño = new javax.swing.JLabel();
        jBtnConstruir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtA_PILA = new javax.swing.JTextArea();
        jBtnAgregar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnPOS_Cima = new javax.swing.JButton();
        jBtnVAL_Cima = new javax.swing.JButton();
        jBtnVaciar = new javax.swing.JButton();
        jLblVacia = new javax.swing.JLabel();
        jLblLlena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UTP - PILAS");

        jLblTamaño.setText("Tamaño");

        jBtnConstruir.setText("Construir Pila");
        jBtnConstruir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConstruirActionPerformed(evt);
            }
        });

        jTxtA_PILA.setColumns(20);
        jTxtA_PILA.setRows(5);
        jScrollPane1.setViewportView(jTxtA_PILA);

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.setToolTipText("");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnPOS_Cima.setText("POS Cima");
        jBtnPOS_Cima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPOS_CimaActionPerformed(evt);
            }
        });

        jBtnVAL_Cima.setText("VAL Cima");
        jBtnVAL_Cima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVAL_CimaActionPerformed(evt);
            }
        });

        jBtnVaciar.setText("Vaciar PILA");
        jBtnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVaciarActionPerformed(evt);
            }
        });

        jLblVacia.setText("¿Vacia?");
        jLblVacia.setToolTipText("Dale Click para saber la respuesta");
        jLblVacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblVaciaMouseClicked(evt);
            }
        });

        jLblLlena.setText("¿Llena?");
        jLblLlena.setToolTipText("Dale Click para saber la respuesta");
        jLblLlena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblLlenaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTamaño)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnPOS_Cima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnVaciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnVAL_Cima, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblVacia, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jBtnConstruir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblLlena)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLblVacia)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLblLlena)
                        .addGap(27, 27, 27)
                        .addComponent(jBtnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnVaciar)
                        .addGap(38, 38, 38)
                        .addComponent(jBtnPOS_Cima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnVAL_Cima))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jBtnConstruir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblTamaño)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConstruirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConstruirActionPerformed

        tamaño = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingresar el tamaño de la PILA:"));
        P = new Pila(tamaño);
        jLblTamaño.setText("Tamaño: " + tamaño);
        Mostrar();
    }//GEN-LAST:event_jBtnConstruirActionPerformed


    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed

        if (P.EstaLlena()) {
            JOptionPane.showMessageDialog(null, "La pila esta llena, nose puede agregar mas elementos");
        } else {
            try {
                int valor = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el valor a agregar: "));

                P.Agregar(valor);
                Mostrar();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un numero valido");
            }
        }
    }//GEN-LAST:event_jBtnAgregarActionPerformed


    private void jBtnPOS_CimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPOS_CimaActionPerformed

        if (P.EstaVacia()) {
            JOptionPane.showMessageDialog(null, "La pila está vacía");
        } else {
            JOptionPane.showMessageDialog(null, "Valor en la cima: " + P.UbicacionCima()); //ValorCima
        }
        Mostrar();
    }//GEN-LAST:event_jBtnPOS_CimaActionPerformed


    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed

        if (P.EstaVacia()) {
            JOptionPane.showMessageDialog(null, "La pila está vacía, no se puede eliminar");
        } else {
            int elementoEliminado = P.Eliminar();
            JOptionPane.showMessageDialog(null, "Elemento eliminado: " + elementoEliminado);
            Mostrar();
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed


    private void jLblVaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVaciaMouseClicked
        if (P.EstaVacia() == true) {
            //System.out.println("Esta vacia");
            JOptionPane.showMessageDialog(null, "La pila esta vacia");
        } else {
            //System.out.println("No esta vacia");
            //System.out.println("Hay" + (P.UbicacionCima() + 1) + "Elementos en la pila");
            JOptionPane.showMessageDialog(null, "La pila no esta vacia. Contiene " + (P.UbicacionCima() + 1) + " elementos");
        }

    }//GEN-LAST:event_jLblVaciaMouseClicked

    private void jLblLlenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblLlenaMouseClicked
        if (P.EstaLlena()) {
            JOptionPane.showMessageDialog(null, "La pila esta llena");
        } else {
            JOptionPane.showMessageDialog(null, "La pila no esta llena. Espacio disponible: " + (P.vectorPila.length - P.UbicacionCima() - 1));
        }
    }//GEN-LAST:event_jLblLlenaMouseClicked

    private void jBtnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVaciarActionPerformed
        P.VaciarPila();
        Mostrar();
    }//GEN-LAST:event_jBtnVaciarActionPerformed

    private void jBtnVAL_CimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVAL_CimaActionPerformed
        if (P.EstaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay valores en la Cima", "Cima", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Valor en la cima: " + P.ValorCima(), "Cima", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnVAL_CimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Pilas().setVisible(true);
            }
        });
    }

    void Mostrar() {
        //Limpiando el TextArea
        jTxtA_PILA.setText("");

        // MOstrar todo los elementos del Vector (de arriba hacia abajo)
        for (int i = P.vectorPila.length - 1; i >= 0; i--) {
            jTxtA_PILA.append(P.vectorPila[i] + "\n");
        }

        //Mostrar informacion Adicional
        if (P.EstaVacia()) {
            //jTxtA_PILA.append("Pila vacia\n");
            //JOptionPane.showMessageDialog(null, "La pila esta VACIA");
            //System.out.println("Estado: Pila VACIA");
        } else if (P.EstaLlena()) {
            //jTxtA_PILA.append("Pila llena\n");
            //JOptionPane.showMessageDialog(null, "La pila esta LLENA");
            //System.out.println("Estado: Pila LLENA");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnConstruir;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnPOS_Cima;
    private javax.swing.JButton jBtnVAL_Cima;
    private javax.swing.JButton jBtnVaciar;
    private javax.swing.JLabel jLblLlena;
    private javax.swing.JLabel jLblTamaño;
    private javax.swing.JLabel jLblVacia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtA_PILA;
    // End of variables declaration//GEN-END:variables
}
