/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Semana12;

import javax.swing.JOptionPane;

/**
 *
 * @author RAT
 */
public class Principal_Colas extends javax.swing.JFrame {

    //Variable global
    int tamaño;
    //Creación de objeto
    Cola C;

    public Principal_Colas() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTamaño = new javax.swing.JLabel();
        jBtnConstruir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtA_PILA = new javax.swing.JTextArea();
        jBtnAgregar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnPOS_Cima = new javax.swing.JButton();
        jBtnVAL_Cima = new javax.swing.JButton();
        jBtnVaciar = new javax.swing.JButton();
        jLblVacia = new javax.swing.JLabel();
        jLblLlena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MORALES");
        setMaximumSize(new java.awt.Dimension(285, 273));
        setMinimumSize(new java.awt.Dimension(285, 273));

        jLblTamaño.setText("Tamaño");

        jBtnConstruir.setText("Construir Cola");
        jBtnConstruir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConstruirActionPerformed(evt);
            }
        });

        jTxtA_PILA.setColumns(20);
        jTxtA_PILA.setRows(5);
        jScrollPane1.setViewportView(jTxtA_PILA);

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.setToolTipText("");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnPOS_Cima.setText("POS Cima");
        jBtnPOS_Cima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPOS_CimaActionPerformed(evt);
            }
        });

        jBtnVAL_Cima.setText("VAL Cima");
        jBtnVAL_Cima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVAL_CimaActionPerformed(evt);
            }
        });

        jBtnVaciar.setText("Vaciar COLA");
        jBtnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVaciarActionPerformed(evt);
            }
        });

        jLblVacia.setText("¿Vacia?");
        jLblVacia.setToolTipText("Dale Click para saber la respuesta");
        jLblVacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblVaciaMouseClicked(evt);
            }
        });

        jLblLlena.setText("¿Llena?");
        jLblLlena.setToolTipText("Dale Click para saber la respuesta");
        jLblLlena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblLlenaMouseClicked(evt);
            }
        });
        jLblLlena.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLblLlenaInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLblTamaño)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jBtnConstruir)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblLlena)
                            .addComponent(jLblVacia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnVAL_Cima, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnPOS_Cima, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnVaciar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jBtnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnVaciar)
                        .addGap(28, 28, 28)
                        .addComponent(jBtnPOS_Cima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnVAL_Cima))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jBtnConstruir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLblVacia)
                                .addGap(19, 19, 19)
                                .addComponent(jLblLlena)))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLblTamaño)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Completo
    private void jBtnConstruirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConstruirActionPerformed

        tamaño = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingresar el tamaño de la COLA:"));
        C = new Cola(tamaño);
        jLblTamaño.setText("Tamaño: " + tamaño);
        Mostrar();
    }//GEN-LAST:event_jBtnConstruirActionPerformed

    // Completo
    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        if (C.estaLlenaCola()) {
            JOptionPane.showMessageDialog(null, "La cola está llena");
        } else {
            try {
                int valor = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el valor a agregar:"));
                C.agregar(valor);
                Mostrar();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un numero valido");
            }
        }
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    // Completo
    private void jBtnPOS_CimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPOS_CimaActionPerformed
        if (C.estaVaciaCola()) {
            JOptionPane.showMessageDialog(null, "La cola está vacía");
        } else {
            JOptionPane.showMessageDialog(null, "Posicion del elemento en la Cima: " + C.inicio);
        }
    }//GEN-LAST:event_jBtnPOS_CimaActionPerformed

    // Completo
    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        if (C.estaVaciaCola()) {
            JOptionPane.showMessageDialog(null, "La Cola esta vacia, nose puede eliminar");
        } else {
            int elementoEliminado = C.eliminar();
            JOptionPane.showMessageDialog(null, "Elemento eliminado: " + elementoEliminado);
            Mostrar();
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    // Completo
    private void jLblVaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVaciaMouseClicked
        if (C.estaVaciaCola() == true) {
            JOptionPane.showMessageDialog(null, "La Cola esta vacia");
        } else {
            JOptionPane.showMessageDialog(null, "La Cola no esta vacia. Contiene " + (C.EnCola()) + " elementos");
        }
    }//GEN-LAST:event_jLblVaciaMouseClicked

    // Completo
    private void jBtnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVaciarActionPerformed
        C.VaciarCola();
        Mostrar();
    }//GEN-LAST:event_jBtnVaciarActionPerformed

    // Completo
    private void jBtnVAL_CimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVAL_CimaActionPerformed
        if (C.estaVaciaCola()) {
            JOptionPane.showMessageDialog(null, "La cola está vacía");
        } else {
            JOptionPane.showMessageDialog(null, "Valor del elemento primero: " + C.VectorCola[0]);
        }
    }//GEN-LAST:event_jBtnVAL_CimaActionPerformed

    // Completo
    private void jLblLlenaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLblLlenaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLblLlenaInputMethodTextChanged

    private void jLblLlenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblLlenaMouseClicked
        if (C.estaLlenaCola()) {
            JOptionPane.showMessageDialog(null, "La Cola esta llena");
        } else {
            JOptionPane.showMessageDialog(null, "La Cola no esta llena. Espacio disponible: " + (C.tamaño - C.EnCola()));
        }
    }//GEN-LAST:event_jLblLlenaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Colas().setVisible(true);
            }
        });
    }

    void Mostrar() {
        //Limpiando el TextArea
        jTxtA_PILA.setText(" ");
        //Cargar el TextArea
        for (int i = 0; i < C.VectorCola.length; i++) {
            if (i > C.fin) {
                jTxtA_PILA.append("0 ");
            } else {
                jTxtA_PILA.append(C.VectorCola[i] + " ");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnConstruir;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnPOS_Cima;
    private javax.swing.JButton jBtnVAL_Cima;
    private javax.swing.JButton jBtnVaciar;
    private javax.swing.JLabel jLblLlena;
    private javax.swing.JLabel jLblTamaño;
    private javax.swing.JLabel jLblVacia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtA_PILA;
    // End of variables declaration//GEN-END:variables
}
